DATA:
    ROOT: '/mnt/nfs/mammal_net/'
    TRAIN_FILE: '/mnt/nfs/mammal_net/annotation/composition/train.csv'
    VAL_FILE: '/mnt/nfs/mammal_net/annotation/composition/test.csv'
    DATASET: mmnet
    NUM_FRAMES: 8
    NUM_CLASSES: 12
    LABEL_LIST: '/mnt/nfs/mammal_net/annotation/behavior_to_id.txt'
    MULTI_CLASSES: False
    NUM_ANIMAL_CLASSES: 173
    ANIMAL_LABEL_LIST: '/mnt/nfs/mammal_net/annotation/genus_to_id.txt'
    INPUT_CHANNEL_NUM: [3, 3]
    INPUT_SIZE: 224
    RELATION_FILE: '/mnt/nfs/mammal_net/annotation/composition/relation.txt'
MODEL:
    ARCH: slowfast
    HEAD_ACT: sigmoid
    DROPOUT_RATE: 0.5
    MODEL_NAME: 'SLOWFAST'
RESNET:
    ZERO_INIT_FINAL_BN: True
    WIDTH_PER_GROUP: 64
    NUM_GROUPS: 1
    DEPTH: 50
    TRANS_FUNC: bottleneck_transform
    STRIDE_1X1: False
    NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
    SPATIAL_STRIDES: [[1, 1], [2, 2], [2, 2], [2, 2]]
    SPATIAL_DILATIONS: [[1, 1], [1, 1], [1, 1], [1, 1]]
NONLOCAL:
    LOCATION: [[[], []], [[], []], [[], []], [[], []]]
    GROUP: [[1, 1], [1, 1], [1, 1], [1, 1]]
    INSTANTIATION: dot_product
SLOWFAST:
    ALPHA: 4
    BETA_INV: 8
    FUSION_CONV_CHANNEL_RATIO: 2
    FUSION_KERNEL_SZ: 7
TRAIN:
    BATCH_SIZE:  16
    LOSS: ce
    ACCUMULATION_STEPS: 4
    EPOCHS: 30
    LR: 0.0375
    LR_POLICY: steps_with_relative_lrs
    LRS: [1, 0.1, 0.01, 0.001, 0.0001, 0.00001]
    STEPS: [0, 41, 49]
    EPOCHS: 200 #57
    MOMENTUM: 0.9
    WEIGHT_DECAY: 1e-4
    WARMUP_EPOCHS: 4.0
    OPTIMIZER: sgd
BN:
    USE_PRECISE_STATS: True
    NUM_BATCHES_PRECISE: 200
    NORM_TYPE: sync_batchnorm
    NUM_SYNC_DEVICES: 1 #4
NUM_SHARDS: 1