DATA:
    ROOT: '/mnt/nfs/mammal_net/'
    TRAIN_FILE: '/mnt/nfs/mammal_net/annotation/composition/train.csv'
    VAL_FILE: '/mnt/nfs/mammal_net/annotation/composition/test.csv'
    DATASET: mmnet
    NUM_FRAMES: 8
    NUM_CLASSES: 12
    LABEL_LIST: '/mnt/nfs/mammal_net/annotation/behavior_to_id.txt'
    MULTI_CLASSES: False
    NUM_ANIMAL_CLASSES: 173
    ANIMAL_LABEL_LIST: '/mnt/nfs/mammal_net/annotation/genus_to_id.txt'
    # FEATURE_ROOT: '/mnt/sdb/data/jingyinuo/mmnet/visual_feature'
    RELATION_FILE: '/mnt/nfs/mammal_net/annotation/composition/relation.txt'
MODEL:
    ARCH: ViT-B/16
    MODEL_NAME: 'VideoPrompt'
TRAIN:
    BATCH_SIZE:  64
    LOSS: 'ce'
    ACCUMULATION_STEPS: 4
    EPOCHS: 30
    LR: 1e-4
    LR_POLICY: cosineannealingwarmrestarts
    WEIGHT_DECAY: 1e-4
    WEIGHT_DECAY_STEPS: 2e5
    WARMUP_EPOCHS: 4.0
    OPTIMIZER: adamw
NUM_WORKERS: 16