DATA:
    ROOT: '/mnt/nfs/mammal_net/'
    TRAIN_FILE: '/mnt/nfs/mammal_net/annotation/composition/train.csv'
    VAL_FILE: '/mnt/nfs/mammal_net/annotation/composition/test.csv'
    DATASET: mmnet
    NUM_FRAMES: 8
    NUM_CLASSES: 12
    LABEL_LIST: '/mnt/nfs/mammal_net/annotation/behavior_to_id.txt'
    MULTI_CLASSES: False
    NUM_ANIMAL_CLASSES: 173
    ANIMAL_LABEL_LIST: '/mnt/nfs/mammal_net/annotation/genus_to_id.txt'
    RELATION_FILE: '/mnt/nfs/mammal_net/annotation/composition/relation.txt'
    description: '/mnt/nfs/mammal_net/annotation/action_description_with_customprompt_v2.csv'
    animal_description: '/mnt/nfs/mammal_net/annotation/animal_description.csv'
MODEL:
    ARCH: ViT-B/16
    MODEL_NAME: 'XCLIP'
TRAIN:
    BATCH_SIZE: 8
    LOSS: 'ce'
    ACCUMULATION_STEPS: 16
    EPOCHS: 30
OUTPUT: 'exp_description_change'