DATA:
    ROOT: '/mnt/nfs/lote/action/'
    TRAIN_FILE: '/mnt/nfs/lote/annotation/LoTE_train.txt' #00 /mnt/sdb/data/jingyinuo/mmnet/annotation/composition/train.csv
    VAL_FILE: '/mnt/nfs/lote/annotation/LoTE_test.txt'
    DATASET: LoTE
    NUM_FRAMES: 8
    NUM_CLASSES: 21
    LABEL_LIST: '/mnt/nfs/lote/annotation/LoTE_label.csv'
    MULTI_CLASSES: False
    NUM_ANIMAL_CLASSES: 11
    ANIMAL_LABEL_LIST: '/mnt/nfs/lote/annotation/animal_label.csv'
    RELATION_FILE: '/mnt/nfs/lote/annotation/relation.txt'
    description: '/mnt/nfs/lote/annotation/action_description_posebits_v2.csv'
    animal_description: '/mnt/nfs/lote/annotation/animal_description.csv'
    SPLIT_DESCRIPTION: False
MODEL:
    ARCH: ViT-B/16
    MODEL_NAME: 'VCW-CLIP'
    HF_FINETUNED_PATH: '/home/nakagawa/large_dataset/ap_10k/clip_adapter_classifier/'
    VCW_TEMPORAL_LAYERS: 2
    VCW_TEMPORAL_HEADS: 8

TRAIN:
    BATCH_SIZE: 8
    LOSS: 'ce'
    ACCUMULATION_STEPS: 16
    EPOCHS: 30

OUTPUT: 'exp_proposed_final_lote'